### PR TITLE
cuda: Restore build support for CUDA 11.3-11.8

### LINKED ISSUE #994: Compiling failed with cuda11.8
Hi there, I am trying to build this against cuda11.8, but having the compiling error below:
```
 nccl_ofi_cuda.c: In function 'nccl_net_ofi_cuda_init':
4.054 nccl_ofi_cuda.c:21:40: error: storage size of 'result' isn't known                                                                                                               
4.054    21 |   enum cudaDriverEntryPointQueryResult result;                                                            \                                                              
4.054       |                                        ^~~~~~                                                                                                                            
4.054 nccl_ofi_cuda.c:69:2: note: in expansion of macro 'RESOLVE_CUDA_FUNCTION'
4.054    69 |  RESOLVE_CUDA_FUNCTION(cuCtxGetDevice);                          
4.054       |  ^~~~~~~~~~~~~~~~~~~~~
4.054 nccl_ofi_cuda.c:23:4: error: too many arguments to function 'cudaGetDriverEntryPoint' 
4.054    23 |    cudaGetDriverEntryPoint(QUOTE(function), (void **)&pfn_##function, cudaEnableDefault, &result); \
4.054       |    ^~~~~~~~~~~~~~~~~~~~~~~
4.054 nccl_ofi_cuda.c:69:2: note: in expansion of macro 'RESOLVE_CUDA_FUNCTION'
4.054    69 |  RESOLVE_CUDA_FUNCTION(cuCtxGetDevice);
4.054       |  ^~~~~~~~~~~~~~~~~~~~~
4.054 In file included from nccl_ofi_cuda.c:10:
4.054 /usr/local/cuda-11.8/include/cuda_runtime_api.h:13032:39: note: declared here
4.054 13032 | extern __host__ cudaError_t CUDARTAPI cudaGetDriverEntryPoint(const char *symbol, void **funcPtr, unsigned long long flags);
4.054       |                                       ^~~~~~~~~~~~~~~~~~~~~~~
4.060 nccl_ofi_cuda.c:26:9: error: 'cudaDriverEntryPointSymbolNotFound' undeclared (first use in this function)
4.060    26 |    case cudaDriverEntryPointSymbolNotFound:                                                        \
4.060       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4.060 nccl_ofi_cuda.c:26:9: note: in definition of macro 'RESOLVE_CUDA_FUNCTION'
4.060    26 |    case cudaDriverEntryPointSymbolNotFound:                                                        \
4.060       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4.060 nccl_ofi_cuda.c:26:9: note: each undeclared identifier is reported only once for each function it appears in
4.060    26 |    case cudaDriverEntryPointSymbolNotFound:                                                        \
4.060       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4.060 nccl_ofi_cuda.c:26:9: note: in definition of macro 'RESOLVE_CUDA_FUNCTION'
4.060    26 |    case cudaDriverEntryPointSymbolNotFound:                                                        \
4.060       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4.066 nccl_ofi_cuda.c:29:9: error: 'cudaDriverEntryPointVersionNotSufficent' undeclared (first use in this function)
4.066    29 |    case cudaDriverEntryPointVersionNotSufficent:                                                   \
4.066       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
cudaGetDriverEntryPoint and cudaDriverEntryPointQueryResult were only introduced in CUDA 12.0. Is there a specific version that still supports cuda11.8 I can use ?

### PR DESCRIPTION
**Pull request by rauteric**
Three commits enabling the plugin to build with CUDA 11.3-11.8, which has been broken for some time.

Fixes: #994 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: m4/check_pkg_nvcc.m4 [hunk 1]
```diff
@@ -78,14 +78,25 @@ AC_DEFUN([CHECK_PKG_NVCC], [
         AC_MSG_NOTICE([NVCC_GENCODE = ${NVCC_GENCODE}])
         ])
 
+  dnl The host build uses -std=c++20, but nvcc only learned c++20 in CUDA
+  dnl 12.0; asking an 11.x nvcc for it is a hard error. Fall back to c++17
+  dnl there, which is enough for the GDAKI device sources.
+  AS_IF([test "${check_nvcc_found}" = "yes"],
+        [AS_IF([test "0${CUDA_MAJOR}" -ge 12],
+               [NVCC_CXXSTD="-std=c++20"],
+               [NVCC_CXXSTD="-std=c++17"])
```
Comment (rauteric) [inline m4/check_pkg_nvcc.m4]: On second thought, this doesn't really make sense. Our code needs to adhere to one version of the C++ standard for all compilers. Switching based on compiler version like this doesn't buy us anything, it will just make us forget we broke CUDA 11 until the next time we try to compile with it.

We should just use C++17 standard uniformly for our CUDA files (which are only the GDAKI functional tests today).

Comment (bwbarrett) [reply m4/check_pkg_nvcc.m4]: I'm ok if we require C++20 for host and C++17 for CUDA, but agree that we should pick one version per "language" and stick to it.

Comment (rauteric) [reply m4/check_pkg_nvcc.m4]: Done

**Review by bwbarrett — APPROVED** [review]

**Review by avivbenchorin — APPROVED** [review]
